// <auto-generated />
namespace PP_HTTP5226.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class teams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teams));
        
        string IMigrationMetadata.Id
        {
            get { return "202402201547546_teams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
